<?php

return [
    ['value' => 0, 'text' => '-- Select Version --'],
    ['value' => 1, 'text' => 'Senayan 3 - Stable 3'],
    ['value' => 2, 'text' => 'Senayan 3 - Stable 4'],
    ['value' => 3, 'text' => 'Senayan 3 - Stable 5'],
    ['value' => 4, 'text' => 'Senayan 3 - Stable 6'],
    ['value' => 5, 'text' => 'Senayan 3 - Stable 7'],
    ['value' => 6, 'text' => 'Senayan 3 - Stable 8'],
    ['value' => 7, 'text' => 'Senayan 3 - Stable 9'],
    ['value' => 8, 'text' => 'Senayan 3 - Stable 10'],
    ['value' => 9, 'text' => 'Senayan 3 - Stable 11'],
    ['value' => 10, 'text' => 'Senayan 3 - Stable 12'],
    ['value' => 11, 'text' => 'Senayan 3 - Stable 13'],
    ['value' => 12, 'text' => 'Senayan 3 - Stable 14 | Seulanga'],
    ['value' => 13, 'text' => 'Senayan 3 - Stable 15 | Matoa'],
    ['value' => 14, 'text' => 'SLiMS 5 | Meranti'],
    ['value' => 15, 'text' => 'SLiMS 7 | Cendana'],
    ['value' => 16, 'text' => 'SLiMS 8 | Akasia'],
    ['value' => 17, 'text' => 'SLiMS 8.2 | Akasia'],
    ['value' => 18, 'text' => 'SLiMS 8.3 | Akasia'],
    ['value' => 19, 'text' => 'SLiMS 8.3.1 | Akasia'],
    ['value' => 20, 'text' => 'SLiMS 9.0.0 | Bulian'],
    ['value' => 21, 'text' => 'SLiMS 9.1.0 | Bulian'],
    ['value' => 22, 'text' => 'SLiMS 9.1.1 | Bulian'],
    ['value' => 23, 'text' => 'SLiMS 9.2.0 | Bulian'],
    ['value' => 24, 'text' => 'SLiMS 9.2.1 | Bulian'],
    ['value' => 25, 'text' => 'SLiMS 9.2.2 | Bulian'],
    ['value' => 26, 'text' => 'SLiMS 9.3.0 | Bulian'],
    ['value' => 27, 'text' => 'SLiMS 9.3.1 | Bulian'],
    ['value' => 28, 'text' => 'SLiMS 9.4.0 | Bulian'],
    ['value' => 29, 'text' => 'SLiMS 9.4.1 | Bulian'],
    ['value' => 30, 'text' => 'SLiMS 9.4.2 | Bulian'],
    ['value' => 31, 'text' => 'SLiMS 9.5.0 | Bulian'],
];